#!/usr/bin/env bash
# PreToolUse hook: block edits to generated/runtime files,
# and require confirmation before editing AI constraint files.

set -euo pipefail

INPUT=$(cat)

# Only care about file-editing tools
TOOL=$(echo "$INPUT" | jq -r '.toolName // empty')
case "$TOOL" in
  create_file|replace_string_in_file|multi_replace_string_in_file|edit_notebook_file) ;;
  *) exit 0 ;;
esac

# Extract the file path from tool input (check common parameter names)
FILE=$(echo "$INPUT" | jq -r '
  .toolInput.filePath // .toolInput.path // .toolInput.file // empty
')

# Nothing to guard if we can't find a path
[ -z "$FILE" ] && exit 0

# Basename for simple matching
BASE=$(basename "$FILE")

# --- Layer 1: Hard deny for generated/runtime files ---
case "$BASE" in
  .coverage-threshold)   REASON="Generated by 'make ratchet'. Run the make target instead." ;;
  requirements.lock)     REASON="Generated by 'make lock' (pip-compile). Edit requirements.txt instead." ;;
  requirements-dev.lock) REASON="Generated by 'make lock' (pip-compile). Edit requirements-dev.txt instead." ;;
  audit.log)             REASON="Runtime audit log. Never edit — append-only by the running system." ;;
  *)                     REASON="" ;;
esac

if [ -n "$REASON" ]; then
  jq -n --arg reason "$REASON" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
  exit 0
fi

# --- Layer 2: Ask confirmation for AI constraint files ---
# These files define the AI's own rules. Edits are allowed but need human approval.
case "$FILE" in
  */.github/hooks/*|*/.github/instructions/*|*/.github/prompts/*|*/.github/agents/*)
    jq -n --arg reason "This file defines AI agent constraints. Confirm you want to edit it." '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "ask",
        permissionDecisionReason: $reason
      }
    }'
    exit 0
    ;;
esac
